import src.markov as markov

text = """
In what ways do the two works you have studied (in form and/or content) question or subvert norms, conventions, or traditions?

Marjane Satrapi’s Persepolis and Haruki Murakami’s The Second Bakery Attack from The Elephant Vanishes both engage deeply with themes of individual agency and societal expectations, yet they do so through distinct narrative forms and techniques. Satrapi critiques the oppressive restrictions of Iranian society, while Murakami subverts the absurdities inherent in capitalist culture. This essay will explore the similarities and contrasts in how these two works question established norms and conventions.

Both works utilize first-person narratives that provide insight into the internal struggles of their protagonists as they navigate societal pressures. In Persepolis, Marjane Satrapi reflects on her personal conflict with the Iranian regime, particularly the clash between modernity and religious tradition. Her statement, “Deep down I was very religious, but as a family we were very modern and avant-garde,” captures her struggle to balance these conflicting identities, emphasizing her agency in a society that seeks to impose strict ideological conformity. Similarly, in The Second Bakery Attack, the couple grapples with an overwhelming, invisible force—hunger—that symbolizes societal pressures. The line, “It was no use. Upon this hunger of ours, as vast and boundless as a Sinai Peninsula, the butter cookies and beer left not a trace,” illustrates their powerlessness against external demands, questioning the absurdity of societal expectations.

Character Development is a critical aspect in both works, showcasing different approaches to rebellion. Persepolis allows for complex character building, as Marjane evolves from a rebellious child to a politically aware adult. This growth is intricately depicted through her experiences, making her journey relatable and impactful. In contrast, the couple in The Second Bakery Attack lacks similar depth; their surreal, anecdotal existence renders them more symbolic than fully realized individuals. This lack of development emphasizes their rebellion against societal norms as an abstract critique rather than a deeply personal journey.

Symbolism also plays a significant role in both narratives. In Persepolis, Satrapi uses visual elements alongside text to enhance her critique of Iranian society. The stark black-and-white illustrations juxtapose the simplicity of childhood innocence against the complexities of political oppression, creating a powerful commentary on identity and resistance. In Murakami's work, hunger acts as a potent symbol for societal pressures, reflecting the absurdity of modern life. The couple's futile attempts to satisfy their hunger through a robbery highlight the disconnect between their desires and the societal expectations that govern their actions.

Narrative Structure further distinguishes the two works. Persepolis, as a graphic novel, employs a linear narrative that allows for a chronological exploration of Marjane’s development and her resistance to the regime. The visual storytelling amplifies the emotional weight of her experiences, making her rebellion not just a personal journey but a broader commentary on societal constraints. Conversely, The Second Bakery Attack features a more fragmented, surreal narrative. This structure mirrors the disorientation felt in modern life, where the couple’s absurd actions and lack of resolution challenge readers to confront the irrationalities of contemporary existence.

Thematic Depth is another area where the two works differ. Marjane’s character in Persepolis resonates with readers through her emotional struggles and evolving worldview, providing a rich critique of gender roles and political oppression in Iran. Her complexity makes her rebellion both personal and political. In contrast, the characters in Murakami’s story, while embodying existential dissatisfaction, remain more detached. Their surreal actions question societal norms in a way that feels intellectual rather than emotional, highlighting the absurdity of life without a clear resolution or growth.

In conclusion, both Persepolis and The Second Bakery Attack effectively question and subvert societal norms through their unique narrative techniques and thematic explorations. While Satrapi’s graphic novel presents a grounded, emotionally rich journey of rebellion against the Iranian regime, Murakami’s short story offers a surreal, symbolic critique of modern capitalist absurdity. Together, they illuminate the diverse ways individuals confront and resist societal conventions, inviting readers to reflect on their own experiences of agency and conformity.

Marjane Satrapi’s Persepolis and Haruki Murakami’s The Second Bakery Attack both engage deeply with themes of individual agency and societal expectations, yet they do so through distinct narrative forms and techniques. Satrapi critiques the oppressive restrictions of Iranian society, while Murakami subverts the absurdities inherent in capitalist culture. This essay will explore the similarities and contrasts in how these two works question established norms and conventions.

Both works employ a first-person narrative that provides insight into the internal struggles of their protagonists as they navigate societal pressures. In Persepolis, Marjane Satrapi reflects on her personal conflict with the Iranian regime, particularly the clash between modernity and religious tradition. Her statement, “Deep down I was very religious, but as a family we were very modern and avant-garde,” captures her struggle to balance these conflicting identities. This duality highlights her agency in a society that seeks to impose strict ideological conformity. Conversely, in The Second Bakery Attack, the couple grapples with an overwhelming, invisible force—hunger—that symbolizes societal pressures. The line, “It was no use. Upon this hunger of ours, as vast and boundless as a Sinai Peninsula, the butter cookies and beer left not a trace,” illustrates their powerlessness against external demands, questioning the absurdity of societal expectations.

Dialogue plays a crucial role in revealing rebellion and subversion in both works. In Persepolis, Marjane voices her confusion and dissent against the regime. Statements like, “It will simply be forbidden” and “Dictator! You are the guardian of the revolution of this house!” exemplify her direct confrontation with authority. The use of dialogue not only conveys her emotional turmoil but also emphasizes the societal constraints she resists. In contrast, the dialogue in The Second Bakery Attack reflects the couple's marital dynamics, subtly subverting societal norms. Phrases such as “Do as I say… I’ll do the rest” and “Whenever my wife expressed such an opinion (or thesis) back then, it reverberated in my ears with the authority of a revelation” illustrate the complex interplay of power and submission within their relationship, suggesting a critique of traditional gender roles.

Despite their thematic similarities, Persepolis and The Second Bakery Attack differ significantly in character development and narrative structure. Persepolis is a graphic novel that allows for complex character building. Marjane is portrayed as a fully realized individual whose rebellion is documented through a detailed narrative of her childhood and adolescence. This direct representation enables readers to witness her growth and resistance against the oppressive political system. In contrast, Murakami’s couple is less developed, presenting a more ambiguous and surreal narrative. Their actions are symbolic rather than directly oppositional, emphasizing a sense of absurdity that characterizes modern life. The couple’s experiences feel anecdotal, inviting readers to interpret their rebellion against societal expectations in a more abstract manner.

The effectiveness of these approaches varies in terms of emotional resonance and thematic depth. Marjane’s detailed journey in Persepolis connects with readers on a personal level, as her evolution from a rebellious child to a politically aware adult provides a nuanced critique of societal norms, particularly regarding gender and oppression in Iran. Her complexity—marked by doubts and emotional struggles—makes her rebellion relatable and impactful. Conversely, the characters in Murakami’s story serve a different purpose; their lack of emotional depth and absurd actions critique the existential detachment prevalent in capitalist society. Although their rebellion raises questions about societal norms, the emotional distance may limit readers’ connections to their plight, rendering the critique more intellectual than visceral.

In conclusion, both Persepolis and The Second Bakery Attack effectively question and subvert societal norms through their unique narrative techniques and thematic explorations. While Satrapi’s graphic novel presents a grounded, emotionally rich journey of rebellion against the Iranian regime, Murakami’s short story offers a surreal, symbolic critique of modern capitalist absurdity. Together, they illuminate the diverse ways individuals confront and resist societal conventions, inviting readers to reflect on their own experiences of agency and conformity.
"""
m = markov.markov(text)
m.fit(mode="remove")

print(m)

print("Generated Sequentially")
out = m.generate_text_sequential(num_words=100, seed=0)
print(out)

print("========================")

print("Generated Recursively")
out = m.generate_text_recursive(num_words=100, seed=0)
print(out)